# -*- coding: utf-8 -*-
"""
翻訳データ定義 + .ts ファイル生成スクリプト（開発用、一度だけ実行）
"""
import xml.etree.ElementTree as ET
import xml.dom.minidom as minidom

# context名 -> [(source_ja, {en, ko, de, ru, fr}), ...]
DATA = {   'MainWindow': [   (   '設定',
                          {   'en': 'Settings',
                              'ko': '설정',
                              'de': 'Einstellungen',
                              'ru': 'Настройки',
                              'fr': 'Paramètres',
                              'zh_CN': '设置',
                              'zh_TW': '設定'}),
                      (   '言語 / Language',
                          {   'en': 'Language',
                              'ko': '언어',
                              'de': 'Sprache',
                              'ru': 'Язык',
                              'fr': 'Langue',
                              'zh_CN': '语言',
                              'zh_TW': '語言'}),
                      (   '言語設定',
                          {   'en': 'Language Settings',
                              'ko': '언어 설정',
                              'de': 'Spracheinstellung',
                              'ru': 'Настройки языка',
                              'fr': 'Paramètres de langue',
                              'zh_CN': '语言设置',
                              'zh_TW': '語言設定'}),
                      (   '言語設定を反映するにはアプリの再起動が必要です。\n今すぐ再起動しますか?',
                          {   'en': 'Restarting the app is required to apply the language '
                                    'setting.\n'
                                    'Restart now?',
                              'ko': '언어 설정을 적용하려면 앱을 재시작해야 합니다.\n지금 재시작하시겠습니까?',
                              'de': 'Zum Übernehmen der Spracheinstellung muss die App neu '
                                    'gestartet werden.\n'
                                    'Jetzt neu starten?',
                              'ru': 'Для применения настроек языка необходимо перезапустить '
                                    'приложение.\n'
                                    'Перезапустить сейчас?',
                              'fr': "Le redémarrage de l'application est nécessaire pour appliquer "
                                    'le paramètre de langue.\n'
                                    'Redémarrer maintenant ?',
                              'zh_CN': '应用语言设置需要重启应用。\n是否立即重启?',
                              'zh_TW': '套用語言設定需要重新啟動應用程式。\n是否立即重新啟動?'}),
                      (   '画像向き自動補正ツール v3.3',
                          {   'en': 'Image Orientation Auto-Correction Tool v3.3',
                              'ko': '이미지 방향 자동 보정 도구 v3.3',
                              'de': 'Automatisches Bildausrichtungs-Korrekturtool v3.3',
                              'ru': 'Инструмент автоматической коррекции ориентации изображений '
                                    'v3.3',
                              'fr': "Outil de correction automatique d'orientation d'image v3.3",
                              'zh_CN': '图像方向自动校正工具 v3.3',
                              'zh_TW': '圖像方向自動校正工具 v3.3'}),
                      (   '画像を読み込んでください',
                          {   'en': 'Please load images',
                              'ko': '이미지를 불러와 주세요',
                              'de': 'Bitte Bilder laden',
                              'ru': 'Загрузите изображения',
                              'fr': 'Veuillez charger des images',
                              'zh_CN': '请载入图像',
                              'zh_TW': '請載入圖像'}),
                      (   'オプション設定',
                          {   'en': 'Options',
                              'ko': '옵션 설정',
                              'de': 'Optionseinstellungen',
                              'ru': 'Настройки параметров',
                              'fr': 'Paramètres des options',
                              'zh_CN': '选项设置',
                              'zh_TW': '選項設定'}),
                      (   '縦横比モード',
                          {   'en': 'Aspect Ratio Mode',
                              'ko': '가로세로 비율 모드',
                              'de': 'Seitenverhältnis-Modus',
                              'ru': 'Режим соотношения сторон',
                              'fr': "Mode de format d'image",
                              'zh_CN': '纵横比模式',
                              'zh_TW': '縱橫比模式'}),
                      (   '🔄 自動',
                          {   'en': '🔄 Auto',
                              'ko': '🔄 자동',
                              'de': '🔄 Automatisch',
                              'ru': '🔄 Авто',
                              'fr': '🔄 Auto',
                              'zh_CN': '🔄 自动',
                              'zh_TW': '🔄 自動'}),
                      (   '📱 縦長',
                          {   'en': '📱 Portrait',
                              'ko': '📱 세로',
                              'de': '📱 Hochformat',
                              'ru': '📱 Портрет',
                              'fr': '📱 Portrait',
                              'zh_CN': '📱 竖屏',
                              'zh_TW': '📱 直式'}),
                      (   '🖥️ 横長',
                          {   'en': '🖥️ Landscape',
                              'ko': '🖥️ 가로',
                              'de': '🖥️ Querformat',
                              'ru': '🖥️ Ландшафт',
                              'fr': '🖥️ Paysage',
                              'zh_CN': '🖥️ 横屏',
                              'zh_TW': '🖥️ 橫式'}),
                      (   '顔検出フィルター',
                          {   'en': 'Face Detection Filter',
                              'ko': '얼굴 인식 필터',
                              'de': 'Gesichtserkennungsfilter',
                              'ru': 'Фильтр распознавания лиц',
                              'fr': 'Filtre de détection de visage',
                              'zh_CN': '人脸检测过滤器',
                              'zh_TW': '人臉偵測篩選器'}),
                      (   '👤 顔検出を有効にする（人物写真の整理に最適）',
                          {   'en': '👤 Enable face detection (best for organizing portrait photos)',
                              'ko': '👤 얼굴 인식 사용 (인물 사진 정리에 최적)',
                              'de': '👤 Gesichtserkennung aktivieren (ideal zum Sortieren von '
                                    'Personenfotos)',
                              'ru': '👤 Включить распознавание лиц (оптимально для сортировки фото '
                                    'людей)',
                              'fr': '👤 Activer la détection de visage (idéal pour trier les photos '
                                    'de personnes)',
                              'zh_CN': '👤 启用人脸检测（最适合整理人物照片）',
                              'zh_TW': '👤 啟用人臉偵測（最適合整理人物照片）'}),
                      (   '📁 画像を読み込む',
                          {   'en': '📁 Load Images',
                              'ko': '📁 이미지 불러오기',
                              'de': '📁 Bilder laden',
                              'ru': '📁 Загрузить изображения',
                              'fr': '📁 Charger des images',
                              'zh_CN': '📁 载入图像',
                              'zh_TW': '📁 載入圖像'}),
                      (   '手動回転調整:',
                          {   'en': 'Manual Rotation:',
                              'ko': '수동 회전 조정:',
                              'de': 'Manuelle Drehung:',
                              'ru': 'Ручной поворот:',
                              'fr': 'Rotation manuelle :',
                              'zh_CN': '手动旋转调整:',
                              'zh_TW': '手動旋轉調整:'}),
                      (   '⟲ 左90°',
                          {   'en': '⟲ Left 90°',
                              'ko': '⟲ 왼쪽 90°',
                              'de': '⟲ Links 90°',
                              'ru': '⟲ Влево 90°',
                              'fr': '⟲ Gauche 90°',
                              'zh_CN': '⟲ 左转90°',
                              'zh_TW': '⟲ 左轉90°'}),
                      (   '⟳ 右90°',
                          {   'en': '⟳ Right 90°',
                              'ko': '⟳ 오른쪽 90°',
                              'de': '⟳ Rechts 90°',
                              'ru': '⟳ Вправо 90°',
                              'fr': '⟳ Droite 90°',
                              'zh_CN': '⟳ 右转90°',
                              'zh_TW': '⟳ 右轉90°'}),
                      (   '⟲ 180°',
                          {   'en': '⟲ 180°',
                              'ko': '⟲ 180°',
                              'de': '⟲ 180°',
                              'ru': '⟲ 180°',
                              'fr': '⟲ 180°',
                              'zh_CN': '⟲ 180°',
                              'zh_TW': '⟲ 180°'}),
                      (   '✓ 選択解除',
                          {   'en': '✓ Clear Selection',
                              'ko': '✓ 선택 해제',
                              'de': '✓ Auswahl aufheben',
                              'ru': '✓ Снять выделение',
                              'fr': '✓ Désélectionner',
                              'zh_CN': '✓ 取消选择',
                              'zh_TW': '✓ 取消選取'}),
                      (   '🗑️ 選択削除',
                          {   'en': '🗑️ Delete Selected',
                              'ko': '🗑️ 선택 삭제',
                              'de': '🗑️ Auswahl löschen',
                              'ru': '🗑️ Удалить выбранное',
                              'fr': '🗑️ Supprimer la sélection',
                              'zh_CN': '🗑️ 删除所选',
                              'zh_TW': '🗑️ 刪除所選'}),
                      (   '💾 元ファイルに反映する',
                          {   'en': '💾 Apply to Original Files',
                              'ko': '💾 원본 파일에 적용',
                              'de': '💾 Auf Originaldateien anwenden',
                              'ru': '💾 Применить к исходным файлам',
                              'fr': "💾 Appliquer aux fichiers d'origine",
                              'zh_CN': '💾 应用到原始文件',
                              'zh_TW': '💾 套用至原始檔案'}),
                      (   '選択: {0}枚',
                          {   'en': 'Selected: {0}',
                              'ko': '선택: {0}장',
                              'de': 'Ausgewählt: {0}',
                              'ru': 'Выбрано: {0}',
                              'fr': 'Sélectionné : {0}',
                              'zh_CN': '已选择: {0} 张',
                              'zh_TW': '已選取: {0} 張'}),
                      (   '✓ 顔検出モデルを読み込みました',
                          {   'en': '✓ Face detection model loaded',
                              'ko': '✓ 얼굴 인식 모델을 불러왔습니다',
                              'de': '✓ Gesichtserkennungsmodell geladen',
                              'ru': '✓ Модель распознавания лиц загружена',
                              'fr': '✓ Modèle de détection de visage chargé',
                              'zh_CN': '✓ 已载入人脸检测模型',
                              'zh_TW': '✓ 已載入人臉偵測模型'}),
                      (   'エラー',
                          {   'en': 'Error',
                              'ko': '오류',
                              'de': 'Fehler',
                              'ru': 'Ошибка',
                              'fr': 'Erreur',
                              'zh_CN': '错误',
                              'zh_TW': '錯誤'}),
                      (   '顔検出モデルの読み込みに失敗しました:\n{0}',
                          {   'en': 'Failed to load face detection model:\n{0}',
                              'ko': '얼굴 인식 모델을 불러오지 못했습니다:\n{0}',
                              'de': 'Gesichtserkennungsmodell konnte nicht geladen werden:\n{0}',
                              'ru': 'Не удалось загрузить модель распознавания лиц:\n{0}',
                              'fr': 'Échec du chargement du modèle de détection de visage :\n{0}',
                              'zh_CN': '人脸检测模型载入失败:\n{0}',
                              'zh_TW': '人臉偵測模型載入失敗:\n{0}'}),
                      (   '画像を選択',
                          {   'en': 'Select Images',
                              'ko': '이미지 선택',
                              'de': 'Bilder auswählen',
                              'ru': 'Выбрать изображения',
                              'fr': 'Sélectionner des images',
                              'zh_CN': '选择图像',
                              'zh_TW': '選擇圖像'}),
                      (   '画像ファイル (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                          {   'en': 'Image Files (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                              'ko': '이미지 파일 (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                              'de': 'Bilddateien (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                              'ru': 'Файлы изображений (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                              'fr': 'Fichiers image (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                              'zh_CN': '图像文件 (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)',
                              'zh_TW': '圖像檔案 (*.jpg *.jpeg *.png *.bmp *.tiff *.webp)'}),
                      (   '読み込みエラー',
                          {   'en': 'Load Error',
                              'ko': '불러오기 오류',
                              'de': 'Ladefehler',
                              'ru': 'Ошибка загрузки',
                              'fr': 'Erreur de chargement',
                              'zh_CN': '载入错误',
                              'zh_TW': '載入錯誤'}),
                      (   '{0} の読み込みに失敗しました:\n{1}',
                          {   'en': 'Failed to load {0}:\n{1}',
                              'ko': '{0}을(를) 불러오지 못했습니다:\n{1}',
                              'de': 'Laden von {0} fehlgeschlagen:\n{1}',
                              'ru': 'Не удалось загрузить {0}:\n{1}',
                              'fr': 'Échec du chargement de {0} :\n{1}',
                              'zh_CN': '载入 {0} 失败:\n{1}',
                              'zh_TW': '載入 {0} 失敗:\n{1}'}),
                      (   '✓ {0}枚の画像を読み込みました',
                          {   'en': '✓ Loaded {0} image(s)',
                              'ko': '✓ {0}장의 이미지를 불러왔습니다',
                              'de': '✓ {0} Bild(er) geladen',
                              'ru': '✓ Загружено {0} изображений',
                              'fr': '✓ {0} image(s) chargée(s)',
                              'zh_CN': '✓ 已载入 {0} 张图像',
                              'zh_TW': '✓ 已載入 {0} 張圖像'}),
                      (   '顔検出実行中...',
                          {   'en': 'Running face detection...',
                              'ko': '얼굴 인식 실행 중...',
                              'de': 'Gesichtserkennung läuft...',
                              'ru': 'Выполняется распознавание лиц...',
                              'fr': 'Détection de visage en cours...',
                              'zh_CN': '正在执行人脸检测...',
                              'zh_TW': '正在執行人臉偵測...'}),
                      (   '顔検出エラー ({0}): {1}',
                          {   'en': 'Face detection error ({0}): {1}',
                              'ko': '얼굴 인식 오류 ({0}): {1}',
                              'de': 'Fehler bei der Gesichtserkennung ({0}): {1}',
                              'ru': 'Ошибка распознавания лиц ({0}): {1}',
                              'fr': 'Erreur de détection de visage ({0}) : {1}',
                              'zh_CN': '人脸检测错误 ({0}): {1}',
                              'zh_TW': '人臉偵測錯誤 ({0}): {1}'}),
                      (   '⚠ {0}枚で顔が未検出（自動選択）',
                          {   'en': '⚠ No face detected in {0} image(s) (auto-selected)',
                              'ko': '⚠ {0}장에서 얼굴이 감지되지 않음 (자동 선택됨)',
                              'de': '⚠ Kein Gesicht in {0} Bild(ern) erkannt (automatisch '
                                    'ausgewählt)',
                              'ru': '⚠ Лицо не обнаружено на {0} изображениях (выбрано '
                                    'автоматически)',
                              'fr': '⚠ Aucun visage détecté sur {0} image(s) (sélection '
                                    'automatique)',
                              'zh_CN': '⚠ {0} 张图像未检测到人脸（已自动选择）',
                              'zh_TW': '⚠ {0} 張圖像未偵測到人臉（已自動選取）'}),
                      (   'EXIF',
                          {   'en': 'EXIF',
                              'ko': 'EXIF',
                              'de': 'EXIF',
                              'ru': 'EXIF',
                              'fr': 'EXIF',
                              'zh_CN': 'EXIF',
                              'zh_TW': 'EXIF'}),
                      (   '肌色検出',
                          {   'en': 'Skin Color Detection',
                              'ko': '피부색 감지',
                              'de': 'Hautfarbenerkennung',
                              'ru': 'Определение цвета кожи',
                              'fr': 'Détection de couleur de peau',
                              'zh_CN': '肤色检测',
                              'zh_TW': '膚色偵測'}),
                      (   '特徴分析',
                          {   'en': 'Feature Analysis',
                              'ko': '특징 분석',
                              'de': 'Merkmalsanalyse',
                              'ru': 'Анализ признаков',
                              'fr': 'Analyse de caractéristiques',
                              'zh_CN': '特征分析',
                              'zh_TW': '特徵分析'}),
                      (   'なし',
                          {   'en': 'None',
                              'ko': '없음',
                              'de': 'Keine',
                              'ru': 'Нет',
                              'fr': 'Aucune',
                              'zh_CN': '无',
                              'zh_TW': '無'}),
                      (   '手動調整',
                          {   'en': 'Manual Adjustment',
                              'ko': '수동 조정',
                              'de': 'Manuelle Anpassung',
                              'ru': 'Ручная настройка',
                              'fr': 'Ajustement manuel',
                              'zh_CN': '手动调整',
                              'zh_TW': '手動調整'}),
                      (   'ファイル名: {0}',
                          {   'en': 'File name: {0}',
                              'ko': '파일명: {0}',
                              'de': 'Dateiname: {0}',
                              'ru': 'Имя файла: {0}',
                              'fr': 'Nom du fichier : {0}',
                              'zh_CN': '文件名: {0}',
                              'zh_TW': '檔案名稱: {0}'}),
                      (   '回転: {0}°',
                          {   'en': 'Rotation: {0}°',
                              'ko': '회전: {0}°',
                              'de': 'Drehung: {0}°',
                              'ru': 'Поворот: {0}°',
                              'fr': 'Rotation : {0}°',
                              'zh_CN': '旋转: {0}°',
                              'zh_TW': '旋轉: {0}°'}),
                      (   '判定方法: {0}',
                          {   'en': 'Detection method: {0}',
                              'ko': '판정 방법: {0}',
                              'de': 'Erkennungsmethode: {0}',
                              'ru': 'Метод определения: {0}',
                              'fr': 'Méthode de détection : {0}',
                              'zh_CN': '判定方法: {0}',
                              'zh_TW': '判定方法: {0}'}),
                      (   '👤 顔検出: {0}人',
                          {   'en': '👤 Faces detected: {0}',
                              'ko': '👤 얼굴 감지: {0}명',
                              'de': '👤 Erkannte Gesichter: {0}',
                              'ru': '👤 Обнаружено лиц: {0}',
                              'fr': '👤 Visages détectés : {0}',
                              'zh_CN': '👤 检测到人脸: {0} 人',
                              'zh_TW': '👤 偵測到人臉: {0} 人'}),
                      (   '❌ 顔未検出',
                          {   'en': '❌ No face detected',
                              'ko': '❌ 얼굴 미감지',
                              'de': '❌ Kein Gesicht erkannt',
                              'ru': '❌ Лицо не обнаружено',
                              'fr': '❌ Aucun visage détecté',
                              'zh_CN': '❌ 未检测到人脸',
                              'zh_TW': '❌ 未偵測到人臉'}),
                      (   '✏️ 変更あり',
                          {   'en': '✏️ Modified',
                              'ko': '✏️ 변경됨',
                              'de': '✏️ Geändert',
                              'ru': '✏️ Изменено',
                              'fr': '✏️ Modifié',
                              'zh_CN': '✏️ 已修改',
                              'zh_TW': '✏️ 已修改'}),
                      (   '✓ {0}枚の画像を回転しました',
                          {   'en': '✓ Rotated {0} image(s)',
                              'ko': '✓ {0}장의 이미지를 회전했습니다',
                              'de': '✓ {0} Bild(er) gedreht',
                              'ru': '✓ Повёрнуто {0} изображений',
                              'fr': '✓ {0} image(s) pivotée(s)',
                              'zh_CN': '✓ 已旋转 {0} 张图像',
                              'zh_TW': '✓ 已旋轉 {0} 張圖像'}),
                      (   '{0}枚の画像の回転処理に失敗しました。\n',
                          {   'en': 'Failed to rotate {0} image(s).\n',
                              'ko': '{0}장의 이미지 회전 처리에 실패했습니다.\n',
                              'de': 'Drehung von {0} Bild(ern) fehlgeschlagen.\n',
                              'ru': 'Не удалось повернуть {0} изображений.\n',
                              'fr': 'Échec de la rotation de {0} image(s).\n',
                              'zh_CN': '{0} 张图像的旋转处理失败。\n',
                              'zh_TW': '{0} 張圖像的旋轉處理失敗。\n'}),
                      (   '失敗した画像は選択状態のまま残っています。\n',
                          {   'en': 'Failed images remain selected.\n',
                              'ko': '실패한 이미지는 선택 상태로 남아 있습니다.\n',
                              'de': 'Fehlgeschlagene Bilder bleiben ausgewählt.\n',
                              'ru': 'Изображения с ошибкой остаются выделенными.\n',
                              'fr': 'Les images en échec restent sélectionnées.\n',
                              'zh_CN': '失败的图像仍保持选中状态。\n',
                              'zh_TW': '失敗的圖像仍保持選取狀態。\n'}),
                      (   '再度お試しいただくか、個別に処理してください。\n\n',
                          {   'en': 'Please try again or process them individually.\n\n',
                              'ko': '다시 시도하거나 개별적으로 처리해 주세요.\n\n',
                              'de': 'Bitte erneut versuchen oder einzeln bearbeiten.\n\n',
                              'ru': 'Повторите попытку или обработайте их по отдельности.\n\n',
                              'fr': 'Veuillez réessayer ou les traiter individuellement.\n\n',
                              'zh_CN': '请重试，或单独处理这些图像。\n\n',
                              'zh_TW': '請重試，或單獨處理這些圖像。\n\n'}),
                      (   '失敗リスト:\n',
                          {   'en': 'Failure list:\n',
                              'ko': '실패 목록:\n',
                              'de': 'Fehlerliste:\n',
                              'ru': 'Список ошибок:\n',
                              'fr': 'Liste des échecs :\n',
                              'zh_CN': '失败列表:\n',
                              'zh_TW': '失敗清單:\n'}),
                      (   '- {0}: {1}\n',
                          {   'en': '- {0}: {1}\n',
                              'ko': '- {0}: {1}\n',
                              'de': '- {0}: {1}\n',
                              'ru': '- {0}: {1}\n',
                              'fr': '- {0} : {1}\n',
                              'zh_CN': '- {0}: {1}\n',
                              'zh_TW': '- {0}: {1}\n'}),
                      (   '回転エラー',
                          {   'en': 'Rotation Error',
                              'ko': '회전 오류',
                              'de': 'Drehfehler',
                              'ru': 'Ошибка поворота',
                              'fr': 'Erreur de rotation',
                              'zh_CN': '旋转错误',
                              'zh_TW': '旋轉錯誤'}),
                      (   '削除確認',
                          {   'en': 'Confirm Deletion',
                              'ko': '삭제 확인',
                              'de': 'Löschbestätigung',
                              'ru': 'Подтверждение удаления',
                              'fr': 'Confirmer la suppression',
                              'zh_CN': '删除确认',
                              'zh_TW': '刪除確認'}),
                      (   '選択した{0}枚の画像を削除しますか?\nこの操作は取り消せません。',
                          {   'en': 'Delete the selected {0} image(s)?\n'
                                    'This action cannot be undone.',
                              'ko': '선택한 {0}장의 이미지를 삭제하시겠습니까?\n이 작업은 취소할 수 없습니다.',
                              'de': 'Die ausgewählten {0} Bild(er) löschen?\n'
                                    'Diese Aktion kann nicht rückgängig gemacht werden.',
                              'ru': 'Удалить выбранные {0} изображений?\n'
                                    'Это действие невозможно отменить.',
                              'fr': 'Supprimer les {0} image(s) sélectionnée(s) ?\n'
                                    'Cette action est irréversible.',
                              'zh_CN': '是否删除已选择的 {0} 张图像?\n此操作无法撤销。',
                              'zh_TW': '是否刪除已選取的 {0} 張圖像?\n此操作無法復原。'}),
                      (   '✓ {0}枚の画像を削除しました',
                          {   'en': '✓ Deleted {0} image(s)',
                              'ko': '✓ {0}장의 이미지를 삭제했습니다',
                              'de': '✓ {0} Bild(er) gelöscht',
                              'ru': '✓ Удалено {0} изображений',
                              'fr': '✓ {0} image(s) supprimée(s)',
                              'zh_CN': '✓ 已删除 {0} 张图像',
                              'zh_TW': '✓ 已刪除 {0} 張圖像'}),
                      (   '情報',
                          {   'en': 'Info',
                              'ko': '정보',
                              'de': 'Information',
                              'ru': 'Информация',
                              'fr': 'Information',
                              'zh_CN': '信息',
                              'zh_TW': '資訊'}),
                      (   '元ファイルに反映する変更はありません。',
                          {   'en': 'There are no changes to apply to the original files.',
                              'ko': '원본 파일에 적용할 변경 사항이 없습니다.',
                              'de': 'Es gibt keine Änderungen, die auf die Originaldateien '
                                    'angewendet werden können.',
                              'ru': 'Нет изменений для применения к исходным файлам.',
                              'fr': "Aucune modification à appliquer aux fichiers d'origine.",
                              'zh_CN': '没有需要应用到原始文件的更改。',
                              'zh_TW': '沒有需要套用至原始檔案的變更。'}),
                      (   'すべての変更を元ファイルに反映しますか?\n\n',
                          {   'en': 'Apply all changes to the original files?\n\n',
                              'ko': '모든 변경 사항을 원본 파일에 적용하시겠습니까?\n\n',
                              'de': 'Alle Änderungen auf die Originaldateien anwenden?\n\n',
                              'ru': 'Применить все изменения к исходным файлам?\n\n',
                              'fr': "Appliquer toutes les modifications aux fichiers d'origine ?\n"
                                    '\n',
                              'zh_CN': '是否将所有更改应用到原始文件?\n\n',
                              'zh_TW': '是否將所有變更套用至原始檔案?\n\n'}),
                      (   '・回転した画像: {0}枚（上書き保存されます）\n',
                          {   'en': '- Rotated images: {0} (will be overwritten)\n',
                              'ko': '・회전한 이미지: {0}장 (덮어쓰기 저장됩니다)\n',
                              'de': '- Gedrehte Bilder: {0} (werden überschrieben)\n',
                              'ru': '- Повёрнутые изображения: {0} (будут перезаписаны)\n',
                              'fr': '- Images pivotées : {0} (seront écrasées)\n',
                              'zh_CN': '・已旋转的图像: {0} 张（将覆盖保存）\n',
                              'zh_TW': '・已旋轉的圖像: {0} 張（將覆蓋儲存）\n'}),
                      (   '・削除した画像: {0}枚（元ファイルも削除されます）\n',
                          {   'en': '- Deleted images: {0} (original files will also be deleted)\n',
                              'ko': '・삭제한 이미지: {0}장 (원본 파일도 삭제됩니다)\n',
                              'de': '- Gelöschte Bilder: {0} (Originaldateien werden ebenfalls '
                                    'gelöscht)\n',
                              'ru': '- Удалённые изображения: {0} (исходные файлы также будут '
                                    'удалены)\n',
                              'fr': "- Images supprimées : {0} (les fichiers d'origine seront "
                                    'également supprimés)\n',
                              'zh_CN': '・已删除的图像: {0} 张（原始文件也将被删除）\n',
                              'zh_TW': '・已刪除的圖像: {0} 張（原始檔案也將被刪除）\n'}),
                      (   '\nこの操作は取り消せません。',
                          {   'en': '\nThis action cannot be undone.',
                              'ko': '\n이 작업은 취소할 수 없습니다.',
                              'de': '\nDiese Aktion kann nicht rückgängig gemacht werden.',
                              'ru': '\nЭто действие невозможно отменить.',
                              'fr': '\nCette action est irréversible.',
                              'zh_CN': '\n此操作无法撤销。',
                              'zh_TW': '\n此操作無法復原。'}),
                      (   '変更を反映',
                          {   'en': 'Apply Changes',
                              'ko': '변경 사항 적용',
                              'de': 'Änderungen anwenden',
                              'ru': 'Применить изменения',
                              'fr': 'Appliquer les modifications',
                              'zh_CN': '应用更改',
                              'zh_TW': '套用變更'}),
                      (   '元ファイルに反映中...',
                          {   'en': 'Applying to original files...',
                              'ko': '원본 파일에 적용 중...',
                              'de': 'Wird auf Originaldateien angewendet...',
                              'ru': 'Применение к исходным файлам...',
                              'fr': "Application aux fichiers d'origine...",
                              'zh_CN': '正在应用到原始文件...',
                              'zh_TW': '正在套用至原始檔案...'}),
                      (   '✓ {0}件の変更を元ファイルに反映しました',
                          {   'en': '✓ Applied {0} change(s) to the original files',
                              'ko': '✓ {0}건의 변경 사항을 원본 파일에 적용했습니다',
                              'de': '✓ {0} Änderung(en) auf die Originaldateien angewendet',
                              'ru': '✓ Применено {0} изменений к исходным файлам',
                              'fr': "✓ {0} modification(s) appliquée(s) aux fichiers d'origine",
                              'zh_CN': '✓ 已将 {0} 项更改应用到原始文件',
                              'zh_TW': '✓ 已將 {0} 項變更套用至原始檔案'}),
                      (   '{0}件の変更を反映しました。\n\n',
                          {   'en': 'Applied {0} change(s).\n\n',
                              'ko': '{0}건의 변경 사항을 적용했습니다.\n\n',
                              'de': '{0} Änderung(en) angewendet.\n\n',
                              'ru': 'Применено {0} изменений.\n\n',
                              'fr': '{0} modification(s) appliquée(s).\n\n',
                              'zh_CN': '已应用 {0} 项更改。\n\n',
                              'zh_TW': '已套用 {0} 項變更。\n\n'}),
                      (   '保存失敗: {0}件\n',
                          {   'en': 'Save failures: {0}\n',
                              'ko': '저장 실패: {0}건\n',
                              'de': 'Speicherfehler: {0}\n',
                              'ru': 'Ошибок сохранения: {0}\n',
                              'fr': "Échecs d'enregistrement : {0}\n",
                              'zh_CN': '保存失败: {0} 项\n',
                              'zh_TW': '儲存失敗: {0} 項\n'}),
                      (   '\n削除失敗: {0}件\n',
                          {   'en': '\nDeletion failures: {0}\n',
                              'ko': '\n삭제 실패: {0}건\n',
                              'de': '\nLöschfehler: {0}\n',
                              'ru': '\nОшибок удаления: {0}\n',
                              'fr': '\nÉchecs de suppression : {0}\n',
                              'zh_CN': '\n删除失败: {0} 项\n',
                              'zh_TW': '\n刪除失敗: {0} 項\n'}),
                      (   '一部エラー',
                          {   'en': 'Partial Errors',
                              'ko': '일부 오류',
                              'de': 'Teilweise Fehler',
                              'ru': 'Частичные ошибки',
                              'fr': 'Erreurs partielles',
                              'zh_CN': '部分错误',
                              'zh_TW': '部分錯誤'}),
                      (   '総画像数: {0}枚',
                          {   'en': 'Total images: {0}',
                              'ko': '총 이미지 수: {0}장',
                              'de': 'Bilder insgesamt: {0}',
                              'ru': 'Всего изображений: {0}',
                              'fr': 'Total des images : {0}',
                              'zh_CN': '总图像数: {0} 张',
                              'zh_TW': '總圖像數: {0} 張'}),
                      (   ' | 変更: {0}枚',
                          {   'en': ' | Modified: {0}',
                              'ko': ' | 변경: {0}장',
                              'de': ' | Geändert: {0}',
                              'ru': ' | Изменено: {0}',
                              'fr': ' | Modifié : {0}',
                              'zh_CN': ' | 已修改: {0} 张',
                              'zh_TW': ' | 已修改: {0} 張'}),
                      (   ' | 選択: {0}枚',
                          {   'en': ' | Selected: {0}',
                              'ko': ' | 선택: {0}장',
                              'de': ' | Ausgewählt: {0}',
                              'ru': ' | Выбрано: {0}',
                              'fr': ' | Sélectionné : {0}',
                              'zh_CN': ' | 已选择: {0} 张',
                              'zh_TW': ' | 已選取: {0} 張'}),
                      (   ' | 顔検出: {0}枚 / 未検出: {1}枚',
                          {   'en': ' | Face detected: {0} / Not detected: {1}',
                              'ko': ' | 얼굴 감지: {0}장 / 미감지: {1}장',
                              'de': ' | Gesicht erkannt: {0} / Nicht erkannt: {1}',
                              'ru': ' | Лицо обнаружено: {0} / Не обнаружено: {1}',
                              'fr': ' | Visage détecté : {0} / Non détecté : {1}',
                              'zh_CN': ' | 检测到人脸: {0} 张 / 未检测到: {1} 张',
                              'zh_TW': ' | 偵測到人臉: {0} 張 / 未偵測到: {1} 張'}),
                      (   '未保存の変更',
                          {   'en': 'Unsaved Changes',
                              'ko': '저장되지 않은 변경 사항',
                              'de': 'Ungespeicherte Änderungen',
                              'ru': 'Несохранённые изменения',
                              'fr': 'Modifications non enregistrées',
                              'zh_CN': '未保存的更改',
                              'zh_TW': '未儲存的變更'}),
                      (   '元ファイルに反映していない変更があります。\nこのまま終了しますか?',
                          {   'en': 'There are changes not yet applied to the original files.\n'
                                    'Exit anyway?',
                              'ko': '원본 파일에 적용하지 않은 변경 사항이 있습니다.\n그대로 종료하시겠습니까?',
                              'de': 'Es gibt Änderungen, die noch nicht auf die Originaldateien '
                                    'angewendet wurden.\n'
                                    'Trotzdem beenden?',
                              'ru': 'Есть изменения, не применённые к исходным файлам.\n'
                                    'Всё равно выйти?',
                              'fr': 'Il y a des modifications non appliquées aux fichiers '
                                    "d'origine.\n"
                                    'Quitter malgré tout ?',
                              'zh_CN': '有尚未应用到原始文件的更改。\n是否仍要退出?',
                              'zh_TW': '有尚未套用至原始檔案的變更。\n是否仍要結束?'}),
                      (   '縦長限定/横長限定モードでは、90°回転はアスペクト比を崩すため無効です。\n180°回転は引き続き使用できます。',
                          {   'en': 'In Portrait-only/Landscape-only mode, 90° rotation is disabled because it would break the aspect ratio.\n180° rotation is still available.',
                              'ko': '세로 전용/가로 전용 모드에서는 종횡비가 깨지므로 90° 회전이 비활성화됩니다.\n180° 회전은 계속 사용할 수 있습니다.',
                              'de': 'Im Modus "Nur Hochformat"/"Nur Querformat" ist die 90°-Drehung deaktiviert, da sie das Seitenverhältnis stören würde.\nDie 180°-Drehung steht weiterhin zur Verfügung.',
                              'ru': 'В режиме «только портрет»/«только альбом» поворот на 90° отключён, так как он нарушит соотношение сторон.\nПоворот на 180° по-прежнему доступен.',
                              'fr': "En mode Portrait uniquement/Paysage uniquement, la rotation à 90° est désactivée car elle romprait le format d'image.\nLa rotation à 180° reste disponible.",
                              'zh_CN': '在仅纵向/仅横向模式下，90°旋转会破坏纵横比，因此已禁用。\n180°旋转仍可使用。',
                              'zh_TW': '在僅直式/僅橫式模式下，90°旋轉會破壞縱橫比，因此已停用。\n180°旋轉仍可使用。'}),
                      (   '⚠ 縦長限定/横長限定モードでは90°回転はできません（180°回転のみ可）',
                          {   'en': '⚠ 90° rotation is not available in Portrait-only/Landscape-only mode (180° only)',
                              'ko': '⚠ 세로 전용/가로 전용 모드에서는 90° 회전을 사용할 수 없습니다 (180°만 가능)',
                              'de': '⚠ 90°-Drehung ist im Modus "Nur Hochformat"/"Nur Querformat" nicht verfügbar (nur 180°)',
                              'ru': '⚠ Поворот на 90° недоступен в режиме «только портрет»/«только альбом» (только 180°)',
                              'fr': "⚠ La rotation à 90° n'est pas disponible en mode Portrait uniquement/Paysage uniquement (180° uniquement)",
                              'zh_CN': '⚠ 仅纵向/仅横向模式下无法使用90°旋转（仅可180°）',
                              'zh_TW': '⚠ 僅直式/僅橫式模式下無法使用90°旋轉（僅可180°）'})],
    'PreviewDialog': [   (   'プレビュー - {0}',
                             {   'en': 'Preview - {0}',
                                 'ko': '미리보기 - {0}',
                                 'de': 'Vorschau - {0}',
                                 'ru': 'Просмотр - {0}',
                                 'fr': 'Aperçu - {0}',
                                 'zh_CN': '预览 - {0}',
                                 'zh_TW': '預覽 - {0}'}),
                         (   '🔍 ズームイン',
                             {   'en': '🔍 Zoom In',
                                 'ko': '🔍 확대',
                                 'de': '🔍 Vergrößern',
                                 'ru': '🔍 Увеличить',
                                 'fr': '🔍 Zoom avant',
                                 'zh_CN': '🔍 放大',
                                 'zh_TW': '🔍 放大'}),
                         (   '🔍 ズームアウト',
                             {   'en': '🔍 Zoom Out',
                                 'ko': '🔍 축소',
                                 'de': '🔍 Verkleinern',
                                 'ru': '🔍 Уменьшить',
                                 'fr': '🔍 Zoom arrière',
                                 'zh_CN': '🔍 缩小',
                                 'zh_TW': '🔍 縮小'}),
                         (   '🔄 リセット',
                             {   'en': '🔄 Reset',
                                 'ko': '🔄 초기화',
                                 'de': '🔄 Zurücksetzen',
                                 'ru': '🔄 Сброс',
                                 'fr': '🔄 Réinitialiser',
                                 'zh_CN': '🔄 重置',
                                 'zh_TW': '🔄 重置'}),
                         (   '閉じる',
                             {   'en': 'Close',
                                 'ko': '닫기',
                                 'de': 'Schließen',
                                 'ru': 'Закрыть',
                                 'fr': 'Fermer',
                                 'zh_CN': '关闭',
                                 'zh_TW': '關閉'}),
                         (   'プレビュー - {0} ({1}%)',
                             {   'en': 'Preview - {0} ({1}%)',
                                 'ko': '미리보기 - {0} ({1}%)',
                                 'de': 'Vorschau - {0} ({1}%)',
                                 'ru': 'Просмотр - {0} ({1}%)',
                                 'fr': 'Aperçu - {0} ({1}%)',
                                 'zh_CN': '预览 - {0} ({1}%)',
                                 'zh_TW': '預覽 - {0} ({1}%)'})]}


LANG_NUMERIC = {
    "en": "en_US", "ko": "ko_KR", "de": "de_DE", "ru": "ru_RU", "fr": "fr_FR",
    "zh_CN": "zh_CN", "zh_TW": "zh_TW",
}



def build_ts(lang: str) -> str:
    ts = ET.Element("TS", version="2.1", language=LANG_NUMERIC[lang])
    for context_name, entries in DATA.items():
        context_el = ET.SubElement(ts, "context")
        ET.SubElement(context_el, "name").text = context_name
        for source, translations in entries:
            message_el = ET.SubElement(context_el, "message")
            ET.SubElement(message_el, "source").text = source
            ET.SubElement(message_el, "translation").text = translations[lang]
    rough = ET.tostring(ts, encoding="unicode")
    pretty = minidom.parseString(rough).toprettyxml(indent="    ")
    # DOCTYPE行を付与(Qt Linguist形式)
    lines = pretty.split("\n")
    lines = [l for l in lines if l.strip()]
    lines.insert(1, "<!DOCTYPE TS>")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import pathlib
    out_dir = pathlib.Path("image_orient_tool/i18n")
    out_dir.mkdir(parents=True, exist_ok=True)
    for lang in LANG_NUMERIC:
        ts_content = build_ts(lang)
        out_path = out_dir / f"app_{lang}.ts"
        out_path.write_text(ts_content, encoding="utf-8")
        print(f"wrote {out_path} ({len(ts_content)} bytes)")
